<!DOCTYPE html>
<html lang= "en">
<head>
	<meta charset = "utf-8"/>
	<meta name="description" content="PHP Footer" />
	<meta name="keywords" 	 content="HTML, CSS, PHP" />
	<meta name="author" 	 content="James Nicholl"/>
</head>
<footer>
	<p>Authors: <a href="mailto:102725583@student.swin.edu.au">Jesse Owen</a> | <a href="mailto:103952502@student.swin.edu.au">Arvan Talaska</a> | <a href="mailto:103995992@student.swin.edu.au">Alex Ozimkovsky-Klein</a> | <a href="mailto:103983670@student.swin.edu.au">James Nicholl</a> | <a href="mailto:103991385@student.swin.edu.au">Zach Chernishov</a></p>
</footer>
</html>