<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<meta name="description" content="Creating Web Applications" />
	<meta name="keywords" 	 content="HTML, CSS, JavaScript" />
	<meta name="author" 	 content="James Nicholl"/>
	<title>Streaming Media Topic Page</title>
	 <link href = "styles/style.css" rel="stylesheet">
</head>
<body>
<h1>Streaming Media</h1> 
	<div class="navbar">
		<a href="index.html">Home</a>
		<a href="topic.html">Topic page</a>
		<a href="quiz.html">Quiz page</a>
		<a href="enhancements.html">Enhancements page</a>
	</div>
	<hr>
</body>
</html>